# Generated by Django 3.0.2 on 2020-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Search',
            },
        ),
    ]
